/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.main;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;
import net.sf.clipsrules.jni.CLIPSException;
import net.sf.clipsrules.jni.CaptureRouter;
import net.sf.clipsrules.jni.Environment;
import net.sf.clipsrules.jni.Router;

/**
 *
 * @author bryan
 */
public class Formulario extends javax.swing.JFrame {
    
    Environment clips;
    CaptureRouter capture;
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            clips = new Environment();
            clips.load("clips/bc_depresion.clp");
            
            this.addWindowListener(new WindowListener() {
                @Override
                public void windowOpened(WindowEvent e) {
                }

                @Override
                public void windowClosing(WindowEvent e) {
                    try {
                        clips.reset();
                    } catch (CLIPSException ex) {
                        ex.printStackTrace();
                    }
                }

                @Override
                public void windowClosed(WindowEvent e) {
                }

                @Override
                public void windowIconified(WindowEvent e) {
                }

                @Override
                public void windowDeiconified(WindowEvent e) {
                }

                @Override
                public void windowActivated(WindowEvent e) {
                }

                @Override
                public void windowDeactivated(WindowEvent e) {
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cHumor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cTension = new javax.swing.JComboBox<>();
        cTemor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cInsomnio = new javax.swing.JComboBox<>();
        cDepresivo = new javax.swing.JComboBox<>();
        cIntelectual = new javax.swing.JComboBox<>();
        cSensorial = new javax.swing.JComboBox<>();
        cMuscular = new javax.swing.JComboBox<>();
        cCardio = new javax.swing.JComboBox<>();
        cResp = new javax.swing.JComboBox<>();
        cGastro = new javax.swing.JComboBox<>();
        cNervioso = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        tNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cGenito = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cConducta = new javax.swing.JComboBox<>();
        textResp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test de Ansiedad - Hamilton");

        jLabel1.setText("Nombre");

        cHumor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));
        cHumor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHumorActionPerformed(evt);
            }
        });

        jLabel2.setText("1. Estado de ánimo ansioso. (Preocupaciones, irritabilidad, entre otros)");

        jLabel3.setText("2. Tensión. (Temblores, llanto fácil, sensación de tensión, entre otros)");

        jLabel4.setText("3. Temores. (A la oscuridad, desconocidos, soledad, multides, entre otros)");

        jLabel5.setText("4. Insomnio. (Dificultad para conciliar el sueño, cansancio al despertar)");

        jLabel6.setText("5. Intelectual (Dificultad para concentrarse, mala memoria)");

        cTension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cTemor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        jLabel7.setText("6. Estado de ánimo deprimido (Pérdida de interés, cambios de humor, entre otros)");

        jLabel8.setText("14. Comportamiento general en la entrevista (Tensión, eructos, entre otros)");

        jLabel9.setText("7. Síntomas musculares (Dolores y molestias musculares, rigidez, entre otros)");

        jLabel10.setText("8. Síntomas sensoriales (Malestar en los cinco sentidos)");

        jLabel11.setText("9. Síntomas cardiovasculares (Taquicardia, palpitaciones, dolores, entre otros)");

        jLabel12.setText("10. Sintomas respiratorios (Sensación de ahogo, disnea, suspiros, entre otros)");

        jLabel13.setText("12. Síntomas genitourinarios (Micción frecuente, impotencia, entre otros)");

        cInsomnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cDepresivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cIntelectual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cSensorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cMuscular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cCardio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cResp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cGastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cNervioso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        jLabel14.setText("11. Síntomas gastrointestinales (Gases, ardor, vómito, estreñimiento, entre otros)");

        cGenito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        jLabel15.setText("13. Síntomas autónomos (Boca seca, rubor, palidez, cefalea, entre otros)");

        cConducta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));
        cConducta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cConductaActionPerformed(evt);
            }
        });

        textResp.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cSensorial, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(cMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jButton1))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cHumor, javax.swing.GroupLayout.Alignment.TRAILING, 0, 164, Short.MAX_VALUE)
                            .addComponent(cTension, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cTemor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cInsomnio, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cIntelectual, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cDepresivo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cCardio, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cResp, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cGastro, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cGenito, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cNervioso, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cConducta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(textResp, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cHumor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cTension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cTemor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cInsomnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cIntelectual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cDepresivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cSensorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11)
                        .addGap(8, 8, 8))
                    .addComponent(cCardio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cGastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cGenito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cNervioso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cConducta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(textResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cHumorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHumorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cHumorActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre, hecho;
        int ansioso, tension, temor, insomnio, intelectual, depresivo, musculares, 
                sensoriales, cardiovasculares, respiratorio, gastrointestinales, 
                genitourinarios, sisAuto, conducta;
        if (tNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese su nombre.");
            return;
        }
        nombre = tNombre.getText();
        ansioso = cHumor.getSelectedIndex();
        tension = cTension.getSelectedIndex();
        temor = cTemor.getSelectedIndex();
        insomnio = cInsomnio.getSelectedIndex();
        intelectual = cIntelectual.getSelectedIndex();
        depresivo = cDepresivo.getSelectedIndex();
        musculares = cMuscular.getSelectedIndex();
        sensoriales = cSensorial.getSelectedIndex();
        cardiovasculares = cCardio.getSelectedIndex();
        respiratorio = cResp.getSelectedIndex();
        gastrointestinales = cGastro.getSelectedIndex();
        genitourinarios = cGenito.getSelectedIndex();
        sisAuto = cNervioso.getSelectedIndex();
        conducta = cConducta.getSelectedIndex();
        
        capture = new CaptureRouter(clips,new String [] 
            {Router.STDOUT, Router.STDERR, Router.STDWRN});
        
        hecho = "(assert "+ 
                    "(persona "+
                        " (nombre-apellido \"" + nombre + "\") "+
                        " (indice-humor-ansioso " + ansioso + ") "+
                        " (indice-tension " + tension + ") "+
                        " (indice-temor " + temor + ") "+
                        " (indice-insomio " + insomnio + ") "+
                        " (indice-funciones-intelectuales " + intelectual + ") "+
                        " (indice-humor-depresivo " + depresivo +") "+
                        " (indice-somanticos-musculares " + musculares +") "+
                        " (indice-somanticos-sensoriales " + sensoriales +") "+
                        " (indice-cardiovasculares " + cardiovasculares +") "+
                        " (indice-respiratorio " + respiratorio+") "+
                        " (indice-gastrointestinales " + gastrointestinales + ") "+
                        " (indice-genitourinarios " + genitourinarios + ") "+
                        " (indice-sistema-nervioso-autonomo " + sisAuto +") "+
                        " (indice-conducta-test " + conducta + ") "+
                   " ) "+
                " )";
        try {
            
            clips.eval(hecho);
            clips.run();
            this.textResp.setText(this.tNombre.getText() + ", "
                    + "tu resultado es: " + capture.getOutput());
            capture.clear();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //clips.destroy();
//        clips.deleteRouter(capture);
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cConductaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cConductaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cConductaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cCardio;
    private javax.swing.JComboBox<String> cConducta;
    private javax.swing.JComboBox<String> cDepresivo;
    private javax.swing.JComboBox<String> cGastro;
    private javax.swing.JComboBox<String> cGenito;
    private javax.swing.JComboBox<String> cHumor;
    private javax.swing.JComboBox<String> cInsomnio;
    private javax.swing.JComboBox<String> cIntelectual;
    private javax.swing.JComboBox<String> cMuscular;
    private javax.swing.JComboBox<String> cNervioso;
    private javax.swing.JComboBox<String> cResp;
    private javax.swing.JComboBox<String> cSensorial;
    private javax.swing.JComboBox<String> cTemor;
    private javax.swing.JComboBox<String> cTension;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField textResp;
    // End of variables declaration//GEN-END:variables
}
