/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.main;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.clipsrules.jni.CLIPSException;
import net.sf.clipsrules.jni.CLIPSLoadException;
import net.sf.clipsrules.jni.CaptureRouter;
import net.sf.clipsrules.jni.Environment;
import net.sf.clipsrules.jni.Router;

/**
 *
 * @author bryan
 */
public class Formulario extends javax.swing.JFrame {
    
    
    Environment clips;
    CaptureRouter theRouter;
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        try {
            initComponents();
            
            clips = new Environment();
            
            clips.load("clips/bc_depresion.clp");
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("adsadasdasdasdasfdAD?F.hgnjsjnfc"+e.toString());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cHumor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cTension = new javax.swing.JComboBox<>();
        cTemor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cInsomnio = new javax.swing.JComboBox<>();
        cDepresivo = new javax.swing.JComboBox<>();
        cIntelectual = new javax.swing.JComboBox<>();
        cSensorial = new javax.swing.JComboBox<>();
        cMuscular = new javax.swing.JComboBox<>();
        cCardio = new javax.swing.JComboBox<>();
        cResp = new javax.swing.JComboBox<>();
        cGastro = new javax.swing.JComboBox<>();
        cNervioso = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        tNombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cGenito = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cConducta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        cHumor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));
        cHumor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHumorActionPerformed(evt);
            }
        });

        jLabel2.setText("Humor");

        jLabel3.setText("Tension");

        jLabel4.setText("Temor");

        jLabel5.setText("Insomnio");

        jLabel6.setText("FuncionIntelectual");

        cTension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cTemor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        jLabel7.setText("HumorDepresivo");

        jLabel8.setText("SomaticoMuscular");

        jLabel9.setText("SomaticoSensorial");

        jLabel10.setText("Cardiovascular");

        jLabel11.setText("Respiratorio");

        jLabel12.setText("Gastrointestinal");

        jLabel13.setText("SistemaNervioso");

        cInsomnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cDepresivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cIntelectual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cSensorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cMuscular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cCardio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cResp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cGastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        cNervioso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        jLabel14.setText("GenitoUrinario");

        cGenito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));

        jLabel15.setText("Conducta");

        cConducta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ausente", "Leve", "Moderado", "Grave", "Muy grave" }));
        cConducta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cConductaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cDepresivo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cIntelectual, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cInsomnio, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cTension, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cHumor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cTemor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButton1))
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cGastro, 0, 164, Short.MAX_VALUE)
                                    .addComponent(cResp, 0, 164, Short.MAX_VALUE)
                                    .addComponent(cCardio, 0, 164, Short.MAX_VALUE)
                                    .addComponent(cSensorial, 0, 164, Short.MAX_VALUE)
                                    .addComponent(cGenito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(cConducta, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cNervioso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cHumor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cTension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cTemor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cIntelectual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cDepresivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cSensorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cCardio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cGastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cInsomnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cGenito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cNervioso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cConducta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cHumorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHumorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cHumorActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre, hecho, input;
        int ansioso, tension, temor, insomnio, intelectual, depresivo, musculares, 
                sensoriales, cardiovasculares, respiratorio, gastrointestinales, 
                genitourinarios, sisAuto, conducta;
        
        nombre = tNombre.getText();
        ansioso = cHumor.getSelectedIndex();
        tension = cTension.getSelectedIndex();
        temor = cTemor.getSelectedIndex();
        insomnio = cInsomnio.getSelectedIndex();
        intelectual = cIntelectual.getSelectedIndex();
        depresivo = cDepresivo.getSelectedIndex();
        musculares = cMuscular.getSelectedIndex();
        sensoriales = cSensorial.getSelectedIndex();
        cardiovasculares = cCardio.getSelectedIndex();
        respiratorio = cResp.getSelectedIndex();
        gastrointestinales = cGastro.getSelectedIndex();
        genitourinarios = cGenito.getSelectedIndex();
        sisAuto = cNervioso.getSelectedIndex();
        conducta = cConducta.getSelectedIndex();
        
        theRouter = new CaptureRouter(clips,new String [] { Router.STDOUT, 
                                                       Router.STDERR,
                                                       Router.STDWRN } );
        
        
        
        hecho = "(assert "+ 
                    "(persona "+
                        " (nombre-apellido \" "+ nombre +" \") "+
                        " (indice-humor-ansioso "+ansioso+") "+
                        " (indice-tension "+tension+") "+
                        " (indice-temor "+temor+") "+
                        " (indice-insomio "+insomnio+") "+
                        " (indice-funciones-intelectuales "+intelectual+") "+
                        " (indice-humor-depresivo "+depresivo+") "+
                        " (indice-somanticos-musculares "+musculares+") "+
                        " (indice-somanticos-sensoriales "+sensoriales+") "+
                        " (indice-cardiovasculares "+cardiovasculares+") "+
                        " (indice-respiratorio "+respiratorio+") "+
                        " (indice-gastrointestinales "+gastrointestinales+") "+
                        " (indice-genitourinarios "+genitourinarios+") "+
                        " (indice-sistema-nervioso-autonomo "+sisAuto+") "+
                        " (indice-conducta-test "+conducta+") "+
                   " ) "+
                " )";
        try {
            
            
            
            clips.reset();
            System.out.println(""+clips.eval(hecho).toString());
            clips.run();
            
            System.out.println("Output: " + theRouter.getOutput());
            theRouter.clear();
            
            
            input = clips.getInputBuffer();
            //System.out.println("INPUT> " + input);
            
        } catch (Exception ex) {
            System.out.println(""+ex.toString());
            Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        //clips.destroy();
        clips.deleteRouter(theRouter);
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cConductaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cConductaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cConductaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cCardio;
    private javax.swing.JComboBox<String> cConducta;
    private javax.swing.JComboBox<String> cDepresivo;
    private javax.swing.JComboBox<String> cGastro;
    private javax.swing.JComboBox<String> cGenito;
    private javax.swing.JComboBox<String> cHumor;
    private javax.swing.JComboBox<String> cInsomnio;
    private javax.swing.JComboBox<String> cIntelectual;
    private javax.swing.JComboBox<String> cMuscular;
    private javax.swing.JComboBox<String> cNervioso;
    private javax.swing.JComboBox<String> cResp;
    private javax.swing.JComboBox<String> cSensorial;
    private javax.swing.JComboBox<String> cTemor;
    private javax.swing.JComboBox<String> cTension;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
}
